# Generated by Django 5.2.7 on 2025-10-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('lms_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('lms_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='edu.course')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'db_table': 'themes',
            },
        ),
        migrations.CreateModel(
            name='Longread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.BigIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.FileField(upload_to='longreads')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longreads', to='edu.course')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longreads', to='edu.theme')),
            ],
            options={
                'verbose_name': 'Longread',
                'verbose_name_plural': 'Longreads',
                'db_table': 'longreads',
            },
        ),
    ]
