# Generated by Django 5.2.6 on 2025-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Longread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lms_id", models.BigIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("theme_id", models.BigIntegerField()),
                ("course_id", models.BigIntegerField()),
                ("contents", models.FileField(upload_to="longreads")),
            ],
            options={
                "verbose_name": "Longread",
                "verbose_name_plural": "Longreads",
                "db_table": "longreads",
            },
        ),
    ]
