# Generated by Django 5.2.6 on 2025-09-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.IntegerField()),
                ("title", models.CharField(max_length=511)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "parent_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edu.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "db_table": "themes",
            },
        ),
        migrations.CreateModel(
            name="Longread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.BigIntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "parent_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edu.course"
                    ),
                ),
                (
                    "parent_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edu.theme"
                    ),
                ),
            ],
            options={
                "verbose_name": "Longread",
                "verbose_name_plural": "Longreads",
                "db_table": "longreads",
            },
        ),
    ]
