# Generated by Django 5.2.6 on 2025-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="longread",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
