# Generated by Django 5.2.7 on 2025-10-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longread',
            name='title',
        ),
        migrations.AddField(
            model_name='longread',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='longread',
            name='longread_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='longread',
            name='theme_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
