# Generated by Django 5.2.7 on 2025-10-20 11:38

import django.db.models.deletion
import edu.models.longread
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_remove_longread_title_longread_course_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longread',
            name='contents',
        ),
        migrations.CreateModel(
            name='LongreadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=edu.models.longread.get_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('longread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='edu.longread')),
            ],
            options={
                'verbose_name': 'Longread File',
                'verbose_name_plural': 'Longread Files',
                'db_table': 'longread_files',
            },
        ),
    ]
