# Generated by Django 5.2.7 on 2025-10-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_remove_longread_contents_longreadfile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='longread',
            constraint=models.UniqueConstraint(fields=('lms_id', 'course_id', 'theme_id'), name='unique_longread_per_course_theme'),
        ),
    ]
